exasol/advanced-analytics-framework

README.md
doc/changes/changes_0.1.0.md
setup.py

#9: Added README file

---

README.md
doc/changes/changes_0.1.0.md
doc/design/event-handler_overhead-evaluation.md
setup.py

#3: Added  event handler overhead evaulation

---

doc/system_requirements.md

#4: Added requirments document

---

exasol_advanced_analytics_framework/event_context/event_context_base.py
exasol_advanced_analytics_framework/event_context/udf_event_context.py
exasol_advanced_analytics_framework/event_handler/event_handler_base.py
exasol_advanced_analytics_framework/udf_framework/create_event_handler_udf.py
tests/test_package/test_event_handlers/event_handler_test.py
tests/unit_tests/event_context/test_udf_event_context.py
tests/unit_tests/udf_framework/mock_event_handlers.py

#29: Fix interface of UDFEventContext

---

doc/changes/changes_0.1.0.md
exasol_advanced_analytics_framework/event_handler/context/proxy/db_object_proxy.py
exasol_advanced_analytics_framework/event_handler/context/proxy/table_like_proxy.py
exasol_advanced_analytics_framework/event_handler/context/top_level_event_handler_context.py
tests/unit_tests/event_handler/test_top_level_event_handler_context.py
tests/unit_tests/udf_framework/test_create_event_handler_udf_mock.py

#30: Sort cleanup queries in reverse order of their creation

---

doc/changes/changes_0.1.0.md
exasol_advanced_analytics_framework/event_context/mock_event_context.py
poetry.lock
tests/unit_tests/event_context/test_mock_event_context.py
tests/unit_tests/udf_framework/test_create_event_handler_udf_mock.py

#34: Added MockEventContext

---

advanced-analytics-framework-0.1.0-1.rockspec
doc/changes/changes_0.1.0.md
exasol_advanced_analytics_framework/event_handler/context/scope_event_handler_context.py
exasol_advanced_analytics_framework/event_handler/context/top_level_event_handler_context.py
exasol_advanced_analytics_framework/lua/src/event_loop.lua
exasol_advanced_analytics_framework/lua/test/test_event_loop.lua
exasol_advanced_analytics_framework/resources/outputs/create_event_loop.sql
exasol_advanced_analytics_framework/udf_framework/create_event_handler_udf.py
scripts/lua_tests.sh
tests/integration_tests/test_event_loop_integration.py
tests/test_package/test_event_handlers/event_handler_test.py
tests/unit_tests/event_handler/test_scope_event_handler_context.py
tests/unit_tests/udf_framework/mock_event_handlers.py
tests/unit_tests/udf_framework/test_create_event_handler_udf_mock.py
tests/utils/test_utils.py

#35: Clean up after EventHandler Exceptions and throw exceptions when a parent EventHandlerContext encounters an unreleased child during release

---

doc/changes/changes_0.1.0.md
poetry.lock
pyproject.toml
setup.py

#42: Update dependencies

---

.gitattributes
advanced-analytics-framework-0.1.0-1.rockspec
exasol_advanced_analytics_framework/deployment/aaf_exasol_lua_script_generator.py
exasol_advanced_analytics_framework/lua/src/query_loop.lua
exasol_advanced_analytics_framework/lua/test/test_query_loop.lua
exasol_advanced_analytics_framework/resources/outputs/create_query_loop.sql
tests/integration_tests/test_query_loop_integration.py

#49: Split functions in lua QueryLoop

---

exasol_advanced_analytics_framework/resources/templates/create_query_handler.jinja.sql
exasol_advanced_analytics_framework/udf_framework/query_handler_runner_udf.py
tests/integration_tests/test_query_loop_integration.py
tests/test_package/test_query_handlers/query_handler_test.py
tests/unit_tests/udf_framework/mock_query_handlers.py
tests/unit_tests/udf_framework/test_query_handler_runner_udf_mock.py

Fix parameter and query_result issues of QueryHandlerRunnerUDF

---

doc/changes/changes_0.1.0.md
exasol_advanced_analytics_framework/query_handler/context/top_level_query_handler_context.py
tests/unit_tests/query_handler/test_scope_query_handler_context.py

#62: Fix bug in ScopeQueryHandlerContext transfer_object_to

---

doc/changes/changes_0.1.0.md
exasol_advanced_analytics_framework/query_handler/context/top_level_query_handler_context.py
exasol_advanced_analytics_framework/query_handler/query/query.py
tests/integration_tests/test_query_loop_integration.py
tests/unit_tests/query_handler/test_scope_query_handler_context.py
tests/unit_tests/query_handler/test_top_level_query_handler_context.py
tests/unit_tests/udf_framework/test_query_handler_runner_udf_mock.py

#69: Fix ScopeQueryHandlerContext invalidate

---

doc/changes/changes_0.1.0.md
exasol_advanced_analytics_framework/query_handler/context/proxy/bucketfs_location_proxy.py
tests/unit_tests/query_handler/test_top_level_query_handler_context.py

#68: Methods called in BucketFSLocationProxy.cleanup can fail and stop the cleanup

---

doc/changes/changes_0.1.0.md
exasol_advanced_analytics_framework/query_handler/context/proxy/bucketfs_location_proxy.py
exasol_advanced_analytics_framework/query_handler/context/proxy/db_object_name_proxy.py
exasol_advanced_analytics_framework/query_handler/context/proxy/db_object_name_with_schema_proxy.py
exasol_advanced_analytics_framework/query_handler/context/proxy/object_proxy.py
exasol_advanced_analytics_framework/query_handler/context/top_level_query_handler_context.py
tests/unit_tests/query_handler/test_scope_query_handler_context.py
tests/unit_tests/query_handler/test_top_level_query_handler_context.py

unified release vs valid naming in top_level_query_handler_context

---

doc/changes/changes_0.1.0.md
exasol_advanced_analytics_framework/query_handler/context/top_level_query_handler_context.py

Made _ScopeQueryHandlerContextBase.get_temporary_path private

---

exasol_advanced_analytics_framework/udf_communication/discovery/localhost/communicator.py
exasol_advanced_analytics_framework/udf_communication/discovery/multi_node/communicator.py
exasol_advanced_analytics_framework/udf_communication/discovery/multi_node/discovery_strategy.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_listener_interface.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_listener_thread.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_peer_state.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_peer_state_builder.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_peer_state_factory.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/connection_establisher.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/connection_establisher_behavior_config.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/connection_establisher_builder.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/connection_establisher_builder_parameter.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/connection_establisher_factory.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/connection_establisher_timeout_config.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/forward_register_peer_config.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/peer_communicator.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/peer_communicator_config.py
tests/udf_communication/peer_communication/test_add_peer.py
tests/udf_communication/peer_communication/test_add_peer_forward.py
tests/udf_communication/peer_communication/test_background_peer_state.py
tests/udf_communication/peer_communication/test_connection_establisher.py
tests/udf_communication/peer_communication/test_connection_establisher_builder.py
tests/udf_communication/peer_communication/test_send_recv.py

#114: Refactored BackgroundPeerState and introduced Parameter Objects

---

doc/changes/changes_0.1.0.md
exasol_advanced_analytics_framework/udf_communication/messages.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/abort_timeout_sender.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/peer_communicator.py
tests/udf_communication/peer_communication/test_abort_timeout_sender.py

#116: Fix AbortTimeoutSender and add reason to Timeout messages

---

.github/actions/prepare_poetry_env/action.yml
.github/workflows/integration_tests_with_db.yaml
.github/workflows/integration_tests_without_db.yaml
.github/workflows/unit_tests.yaml
noxfile.py

#126: Split GitHub workflow for tests into separate workflows for each test type

---

exasol_advanced_analytics_framework/udf_communication/messages.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_listener_thread.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/frontend_peer_state.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/payload_message_sender.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/payload_message_sender_factory.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/payload_message_sender_timeout_config.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/payload_sender.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/payload_sender_factory.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/sender.py
tests/unit_tests/udf_communication/peer_communication/test_payload_message_sender.py
tests/unit_tests/udf_communication/peer_communication/test_payload_sender.py
tests/unit_tests/udf_communication/test_messages.py

#137: Added PayloadSender

---

exasol_advanced_analytics_framework/udf_communication/peer_communicator/payload_receiver.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/payload_receiver_factory.py
tests/unit_tests/udf_communication/peer_communication/test_payload_receiver.py

#138: Added PayloadReceiver

---

exasol_advanced_analytics_framework/udf_communication/messages.py
poetry.lock
pyproject.toml
tests/unit_tests/udf_communication/test_messages.py

#140: Improved tests for messages

---

exasol_advanced_analytics_framework/udf_communication/peer_communicator/payload_handler.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/payload_handler_builder.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/payload_handler_factory.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/payload_sender.py
tests/unit_tests/udf_communication/peer_communication/test_payload_handler.py

#139: Added PayloadHandler

---

exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_listener_thread.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/connection_establisher_builder.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/register_peer_forwarder_builder.py

#149: Refactored create_background_peer_state_builder

---

exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_listener_interface.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_listener_thread.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_peer_state.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/frontend_peer_state.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/peer_communicator.py
tests/unit_tests/udf_communication/peer_communication/test_background_peer_state.py

#154: Move sending messages to peers to the BackgroundPeerState

---

exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_listener_interface.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_listener_thread.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/frontend_peer_state.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/peer_communicator.py
tests/integration_tests/without_db/udf_communication/peer_communication/test_send_recv.py

#155: Use out_control_socket to forward received Payload messages to the Frontend

---

exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_listener_thread.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_peer_state.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_peer_state_builder.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_peer_state_factory.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/payload_handler_builder.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/payload_receiver.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/payload_receiver_factory.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/payload_sender_factory.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/peer_communicator_config.py
tests/integration_tests/without_db/udf_communication/peer_communication/test_send_recv.py
tests/unit_tests/udf_communication/peer_communication/test_background_peer_state.py
tests/unit_tests/udf_communication/peer_communication/test_connection_establisher_builder.py

#151: Inject PayloadHandler into BackgroundPeerState.

---

exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_listener_thread.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_peer_state.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_peer_state_builder.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_peer_state_factory.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/peer_communicator_config.py
tests/unit_tests/udf_communication/peer_communication/test_background_peer_state.py

#162: Inject ConnectionCloser into BackgroundPeerState

---

exasol_advanced_analytics_framework/udf_communication/messages.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_listener_interface.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_listener_thread.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_peer_state.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_peer_state_builder.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_peer_state_factory.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_thread/connection_closer/close_connection_sender.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_thread/connection_closer/connection_closer.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/connection_establisher.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/frontend_peer_state.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/peer_communicator.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/peer_communicator_config.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/synchronize_connection_sender.py
tests/integration_tests/without_db/udf_communication/peer_communication/test_add_peer_forward_and_close.py
tests/unit_tests/udf_communication/peer_communication/background_thread/connection_closer/test_connection_closer.py
tests/unit_tests/udf_communication/peer_communication/test_background_peer_state.py
tests/unit_tests/udf_communication/peer_communication/test_connection_establisher.py
tests/unit_tests/udf_communication/peer_communication/test_synchronize_connection_sender.py

#164: Integrate ConnectionCloser

---

exasol_advanced_analytics_framework/udf_communication/messages.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_listener_thread.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_peer_state.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/background_thread/connection_closer/close_connection_sender.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/frontend_peer_state.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/payload_message_sender.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/payload_message_sender_timeout_config.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/payload_receiver.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/peer_communicator.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/synchronize_connection_sender.py
exasol_advanced_analytics_framework/udf_communication/socket_factory/fault_injection.py
tests/integration_tests/without_db/udf_communication/peer_communication/test_send_recv.py
tests/unit_tests/udf_communication/peer_communication/test_background_peer_state.py
tests/unit_tests/udf_communication/peer_communication/test_payload_handler.py
tests/unit_tests/udf_communication/peer_communication/test_payload_receiver.py
tests/unit_tests/udf_communication/peer_communication/test_payload_sender.py
tests/unit_tests/udf_communication/peer_communication/test_synchronize_connection_sender.py

#152: Use payload handler for sending and receiving

---

exasol_advanced_analytics_framework/udf_communication/peer_communicator/peer_communicator.py
tests/integration_tests/without_db/udf_communication/peer_communication/test_poll.py

#166: Added poll_peers to PeerCommunicator

---

exasol_advanced_analytics_framework/udf_communication/communicator.py
exasol_advanced_analytics_framework/udf_communication/gather_operation.py
exasol_advanced_analytics_framework/udf_communication/messages.py
exasol_advanced_analytics_framework/udf_communication/peer_communicator/peer_communicator.py
tests/integration_tests/without_db/udf_communication/test_communicator.py
tests/integration_tests/without_db/udf_communication/test_gather.py
tests/unit_tests/udf_communication/test_gather_operation.py

#103: Add gather collective operation 

---

doc/changes/changes_0.1.0.md
exasol_advanced_analytics_framework/lua/src/query_loop.lua
exasol_advanced_analytics_framework/lua/test/test_exasol_tools.lua
exasol_advanced_analytics_framework/lua/test/test_query_handler_runner.lua
exasol_advanced_analytics_framework/lua/test/test_query_loop.lua
exasol_advanced_analytics_framework/resources/outputs/create_query_loop.sql
exasol_advanced_analytics_framework/udf_framework/query_handler_runner_udf.py
tests/integration_tests/with_db/test_query_loop_integration.py

#191: Renamed UDF json element "parameters" to "parameter"

---

.github/workflows/build-and-publish.yml
.github/workflows/ci.yml
doc/changes/changes_0.1.0.md
exasol_advanced_analytics_framework/slc.py

Closes #175 
incl. adding SLC as asset to the GitHub release

 #175: Prepare releasing AAF to PyPi 

---

SECURITY.md
doc/changes/unreleased.md
exasol/analytics/query_handler/query/select.py
exasol/analytics/schema/__init__.py
exasol/analytics/schema/column.py
exasol/analytics/schema/column_type.py
exasol/analytics/schema/dbobject_type.py
exasol/analytics/schema/dboperation_type.py
exasol/analytics/schema/values.py
tests/unit_tests/data_science_utils/schema/test_column.py
tests/unit_tests/data_science_utils/schema/test_column_type.py
tests/unit_tests/data_science_utils/schema/test_values.py
tests/unit_tests/query_handler/test_select.py

Enhanced the existing classes in exasol.analytics.schema in order to provide some convenience for creating and maintaining the AAF Audit Log.
Closes #259

Enhanced Schema classes

---

doc/changes/unreleased.md
exasol/analytics/query_handler/query/interface.py
exasol/analytics/schema/__init__.py
exasol/analytics/schema/statements.py
tests/unit_tests/data_science_utils/schema/test_insert_statement.py

#266 Created Insert Statement Formatter incl. unit tests

---

doc/changes/changelog.md
doc/changes/changes_0.4.1.md
doc/changes/unreleased.md
exasol/analytics/query_handler/query/result/python_query_result.py
pyproject.toml
version.py

 #281: Fixed imports in python_query_result.py

---

.github/workflows/ci.yml
README.md
doc/changes/unreleased.md
doc/user_guide/user_guide.md

 #283: Updated README and user guide
